import LocalizedStrings from "react-localization"

export const strings = new LocalizedStrings({
  en: {
    login: {
      logoUrl: "/media/logo/AlumniNetworkEn/png/logo-no-background.png",
    },
    navbar: {
      title: "Network Alumni",
      login: "Log in",
      logout: "Log out",
      navMenuList: [
        "Timeline",
        "Groups",
        "Topics",
        "Calendar",
        "Dashboard",
        "Profile",
      ],
    },
    groupList: {
      title: "Group List",
      createNew: "Create new group",
      member: "Member",
      private: "Private",
    },
    group: {
      title: "Group posts",
      createNew: "Create new post",
      group: "In group: ",
      groups: "Group/s: ",
    },
    topicList: {
      title: "Topic List",
      createNew: "Create new topic",
      member: "Member",
    },
    topic: {
      title: "Topic posts",
      createNew: "Create new post",
      topics: "Topic/s: ",
      topic: "In topic: ",
    },
    profilePage: {
      firstName: "Firstname",
      lastName: "Lastname",
      userStatus: "Status",
      funFact: "Fun Fact",
      bio: "Bio",
      pictureUrl: "Profilepicture's URL",
      errorMessage: "Something went wrong",
      success: "Profile updated",
    },
    common: {
      edit: "Edit",
      create: "Create",
      save: "Save",
      submit: "Submit",
      close: "Close",
      calendar: "Calendar",
      search: "Search",
      invite: "Invite",
      join: "Join",
      leave: "Leave",
      cancel: "Cancel",
      start: "Starts",
      viewEvent: "View event",
    },
    timeline: {
      title: "Timeline",
      createNew: "Create new post",
      group: "In group: ",
      topic: "In topic: ",
      startingAt: "Starting at: ",
    },
    dashboard: {
      userDashboard: "User dashboard",
      posts: "Posts",
    },
    calendar: {
      text: "Find events to attend via your intrests!",
    },
    createPostForm: {
      title: "Create new post",
      postTitle: "Post Title",
      group: "Group",
      topic: "Topic",
      content: "Content",
      none: "None",
      post: "Post!",
      newGroup: "Create New Group",
      newTopic: "Create New Topic",
      titleAnswer: "Answer to post"
    },
    createGroup: {
      newGroup: "Create New Group",
      groupName: "Group Name",
      groupDescription: "Group Description",
      privacy: "Privacy",
      public: "Public",
      private: "Private",
      addGroup: "Add Group",
    },
    createTopic: {
      newTopic: "Create New Topic",
      topicName: "Topic Name",
      topicDescription: "Topic Description",
      addTopic: "Add Topic",
    },
    postThread: {
      reply: "Reply to",
      wrongPostId: "This post doesn't exist",
      answer: "Answer",
      edit: "Edit post",
    },
    createEvent: {
      title: "Create new event",
      eventName: "Event name",
      description: "Description",
      group: "Group",
      topic: "Topic",
      joining: "Allow joining",
      inviteUsers: "Invite users",
      startTime: "Start date & time",
      endTime: "End time",
      createEvent: "Create event",
    },
    eventThread: {
      wrongId: "This event doesn't exist.",
      noChilds: "No comments.",
    },
    editPost: {
      editTitle: "Edit post"
    }
  },
  fi: {
    login: {
      logoUrl: "/media/logo/AlumniNetworkFi/png/logo-no-background.png",
    },
    navbar: {
      title: "Network Alumni",
      login: "Kirjaudu sisään",
      logout: "Kirjaudu ulos",
      navMenuList: [
        "Aikajana",
        "Ryhmät",
        "Aiheet",
        "Kalenteri",
        "Kojelauta",
        "Profiili",
      ],
    },
    groupList: {
      title: "Ryhmä listaus",
      createNew: "Luo uusi ryhmä",
      member: "Jäsen",
      private: "Yksityinen",
    },
    group: {
      title: "Ryhmän julkaisut",
      createNew: "Luo uusi posti",
      group: "Ryhmässä: ",
      groups: "Ryhmä/t: ",
    },
    topicList: {
      title: "Aihe listaus",
      createNew: "Luo uusi aihe",
      member: "Jäsen",
    },
    topic: {
      title: "Aiheen julkaisut",
      createNew: "Luo uusi posti",
      topic: "Aiheessa: ",
      topics: "Aiheessa: ",
    },
    profilePage: {
      firstName: "Etunimi",
      lastName: "Sukunimi",
      userStatus: "Status",
      funFact: "Hauska fakta",
      bio: "kuvaus",
      pictureUrl: "Profiilikuvan URL",
      errorMessage: "Jotain meni pieleen",
      success: "Profiili päivitetty",
    },
    common: {
      edit: "Muokkaa",
      create: "Luo",
      save: "Tallenna",
      submit: "Julkaise",
      close: "Sulje",
      calendar: "Kalenteri",
      search: "Etsi",
      invite: "Kutsu",
      join: "Liity",
      leave: "Poistu",
      cancel: "Peruuta",
      start: "Alkaa",
      viewEvent: "Katso tapahtuma",
    },
    timeline: {
      title: "Aikajana",
      createNew: "Luo uusi postaus",
      group: "Ryhmässä: ",
      topic: "Aiheessa: ",
      startingAt: "Alkaa:",
    },
    dashboard: {
      userDashboard: "Käyttäjän kojelauta",
      posts: "Postaukset",
    },
    createPostForm: {
      title: "Luo uusi viesti",
      postTitle: "Otsikko",
      group: "Ryhmä",
      topic: "Aihe",
      content: "Viesti",
      none: "Tyhjä",
      post: "Julkaise!",
      newGroup: "Luo uusi ryhmä",
      newTopic: "Luo uusi aihe",
      titleAnswer: "Vastaa julkaisuun",
    },
    createGroup: {
      newGroup: "Luo uusi ryhmä",
      groupName: "Ryhmän nimi",
      groupDescription: "Ryhmän kuvaus",
      privacy: "Yksityisyys",
      public: "Julkinen",
      private: "Yksityinen",
      addGroup: "Lisää ryhmä",
    },
    createTopic: {
      newTopic: "Luo uusi aihe",
      topicName: "Aiheen Nimi",
      topicDescription: "Aiheen kuvaus",
      addTopic: "Lisää Aihe",
    },
    postThread: {
      reply: "Vastaa",
      wrongPostId: "Tälläistä julkaisua ei ole olemassa",
      answer: "Vastaa",
      edit: "Muokkaa julkaisua",
    },
    createEvent: {
      title: "Luo uusi tapahtuma",
      eventName: "Tapahtuman nimi",
      description: "Kuvaus",
      group: "Ryhmä",
      topic: "Aihe",
      joining: "Salli liittyminen",
      inviteUsers: "Kutsu käyttäjiä",
      startTime: "Aloituspäivä & aika",
      endTime: "Lopetusaika",
      createEvent: "Luo tapahtuma",
    },
    calendar: {
      text: "Löydä mieleisiäsi tapahtumia!",
    },
    eventThread: {
      wrongId: "Tälläistä tapahtumaa ei ole olemassa.",
      noChilds: "Ei kommentteja.",
    },
    editPost: {
      editTitle: "Muokkaa julkaisua"
    }
  },
})
