import LocalizedStrings from "react-localization"

export const strings = new LocalizedStrings({
  en: {
    login: {
      logoUrl: "/media/logo/AlumniNetworkEn/png/logo-no-background.png",
    },
    navbar: {
      title: "Network Alumni",
      login: "Log in",
      logout: "Log out",
      navMenuList: [
        "Timeline",
        "Groups",
        "Topics",
        "Calendar",
        "Dashboard",
        "Profile",
      ],
    },
    groupList: {
      title: "Group List",
      createNew: "Create new group",
      member: "Member",
      private: "Private",
    },
    group: {
      title: "Posts",
      createNew: "Create new post",
      group: "In group: ",
      groups: "Group/s: ",
    },
    topicList: {
      title: "Topic List",
      createNew: "Create new topic",
      member: "Member",
    },
    topic: {
      title: "Posts",
      createNew: "Create new post",
      topics: "Topic/s: ",
      topic: "In topic: ",
    },
    profilePage: {
      firstName: "Firstname",
      lastName: "Lastname",
      userStatus: "Status",
      funFact: "Fun Fact",
      bio: "Bio",
      pictureUrl: "Profilepicture's URL",
    },
    common: {
      edit: "Edit",
      create: "Create",
      save: "Save",
      submit: "Submit",
      close: "Close",
      calendar: "Calendar",
      search: "Search",
      invite: "Invite",
      join: "Join",
      leave: "Leave",
      start: "Starts",
    },
    timeline: {
      title: "Timeline",
      createNew: "Create new post",
      group: "In group: ",
      topic: "In topic: ",
      startingAt: "Starting at: ",
    },
    dashboard: {
      userDashboard: "User dashboard",
      posts: "Posts",
    },
    calendar: {
      text: "Find events to attend via your intrests!",
    },
    postThread: {
      reply: "Reply to",
      wrongPostId: "This post doesn't exist",
    },
  },
  fi: {
    login: {
      logoUrl: "/media/logo/AlumniNetworkFi/png/logo-no-background.png",
    },
    navbar: {
      title: "Network Alumni",
      login: "Kirjaudu sisään",
      logout: "Kirjaudu ulos",
      navMenuList: [
        "Aikajana",
        "Ryhmät",
        "Aiheet",
        "Kalenteri",
        "Kojelauta",
        "Profiili",
      ],
    },
    groupList: {
      title: "Ryhmä listaus",
      createNew: "Luo uusi ryhmä",
      member: "Jäsen",
      private: "Yksityinen",
    },
    group: {
      title: "Postit",
      createNew: "Luo uusi posti",
      group: "Ryhmässä: ",
      groups: "Ryhmä/t: ",
    },
    topicList: {
      title: "Aihe listaus",
      createNew: "Luo uusi aihe",
      member: "Jäsen",
    },
    topic: {
      title: "Postit",
      createNew: "Luo uusi posti",
      topic: "Aiheessa: ",
      topics: "Aiheessa: ",
    },
    profilePage: {
      firstName: "Etunimi",
      lastName: "Sukunimi",
      userStatus: "Status",
      funFact: "Hauska fakta",
      bio: "kuvaus",
      pictureUrl: "Profiilikuvan URL",
    },
    common: {
      edit: "Muokkaa",
      create: "Luo",
      save: "Tallenna",
      submit: "Julkaise",
      close: "Sulje",
      calendar: "Kalenteri",
      search: "Etsi",
      invite: "Kutsu",
      join: "Liity",
      leave: "Poistu",
      start: "Alkaa",
    },
    timeline: {
      title: "Aikajana",
      createNew: "Luo uusi postaus",
      group: "Ryhmässä: ",
      topic: "Aiheessa: ",
      startingAt: "Alkaa:",
    },
    dashboard: {
      userDashboard: "Käyttäjän kojelauta",
      posts: "Postaukset",
    },
    postThread: {
      reply: "Vastaus käyttäjälle",
      wrongPostId: "Tälläistä julkaisua ei ole olemassa",
    },
  },
})
